//Catgory
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const SEARCH_CATEGORIES = 'SEARCH_CATEGORIES';
export const FILTERLIST_CATEGORIES = 'FILTERLIST_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
